version: "3.8"

services:
  app-server:
    container_name: todos_api
    build: .
    ports:
      - "3030:3030"
    restart: on-failure
    volumes:
      - api:/usr/src/app
    depends_on:
      - fullstack-mysql
    networks:
      - fullstack
    tty: true
  
  fullstack-mysql:
    image: mysql:latest
    container_name: full_db_mysql
    ports: 
      - 3306:3306
    environment: 
      - MYSQL_ROOT_HOST="${MYSQL_HOST} 
      - MYSQL_USER="${MYSQL_USER}"
      - MYSQL_PASSWORD="${MYSQL_PASSWORD}"
      - MYSQL_DATABASE="${MYSQL_DBNAME}"
      - MYSQL_ROOT_PASSWORD="${MYSQL_PASSWORD}"
    volumes:
      - database_mysql:/var/lib/mysql
    networks:
      - fullstack

volumes:
  api:
  database_mysql:                  

# Networks to be created to facilitate communication between containers
networks:
  fullstack:
    driver: bridge