version: "3.8"

services:
  api-server:
    container_name: todos
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3030:3030"
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DBNAME: todo_api_db
      # GOMAXPROCS: 4
    tty: true
    restart: always