CREATE TABLE IF NOT EXISTS activities(  
    id int NOT NULL AUTO_INCREMENT PRIMARY KEY,
    email VARCHAR(100),
    title VARCHAR(100),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME ON UPDATE CURRENT_TIMESTAMP DEFAULT NULL,
    deleted_at DATETIME DEFAULT NULL
) DEFAULT CHARSET UTF8;